# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "railroadmap"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seiji Munetoh"]
  s.date = "2013-11-03"
  s.description = "TBD"
  s.email = "seiji.munetoh@gmail.com"
  s.executables = ["railroadmap"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "History.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/railroadmap",
    "lib/railroadmap.rb",
    "lib/railroadmap/cli.rb",
    "lib/sorcerer.rb",
    "lib/sorcerer/resource.rb",
    "lib/sorcerer/subexpression.rb",
    "lib/sorcerer/version.rb",
    "railroadmap.gemspec",
    "spec/railroadmap_spec.rb",
    "spec/rails/abstraction/block_spec.rb",
    "spec/rails/abstraction/controller_spec.rb",
    "spec/rails/abstraction/depot_spec.rb",
    "spec/rails/abstraction/model_spec.rb",
    "spec/rails/abstraction/ruby_spec.rb",
    "spec/rails/abstraction/sample/app/controllers/application_controller.rb",
    "spec/rails/abstraction/sample/app/controllers/devise/confirmations_controller.rb",
    "spec/rails/abstraction/sample/app/controllers/tags_controller.rb",
    "spec/rails/abstraction/sample/app/controllers/tasks_controller.rb",
    "spec/rails/abstraction/sample/app/controllers/users_controller.rb",
    "spec/rails/abstraction/sample/app/controllers/welcome_controller.rb",
    "spec/rails/abstraction/sample/app/models/tag.rb",
    "spec/rails/abstraction/sample/app/models/tag_task.rb",
    "spec/rails/abstraction/sample/app/models/task.rb",
    "spec/rails/abstraction/sample/app/models/user.rb",
    "spec/rails/abstraction/sample/app/views/tasks/_form.html.erb",
    "spec/rails/abstraction/sample/app/views/tasks/edit.html.erb",
    "spec/rails/abstraction/sample/app/views/tasks/index.html.erb",
    "spec/rails/abstraction/sample/app/views/tasks/new.html.erb",
    "spec/rails/abstraction/sample/app/views/tasks/show.html.erb",
    "spec/rails/abstraction/sample/db/schema.rb",
    "spec/rails/abstraction/testenv.rb.sample",
    "spec/rails/abstraction/timefliesby_spec.rb",
    "spec/rails/abstraction/view_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/munetoh/railroadmap"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Generate behavior model of Ruby on Rails Web application."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ripper2ruby>, [">= 0"])
      s.add_runtime_dependency(%q<ruby2ruby>, [">= 0"])
      s.add_runtime_dependency(%q<sexp_processor>, [">= 0"])
      s.add_runtime_dependency(%q<ruby_parser>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-graphviz>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, [">= 0"])
    else
      s.add_dependency(%q<ripper2ruby>, [">= 0"])
      s.add_dependency(%q<ruby2ruby>, [">= 0"])
      s.add_dependency(%q<sexp_processor>, [">= 0"])
      s.add_dependency(%q<ruby_parser>, [">= 0"])
      s.add_dependency(%q<ruby-graphviz>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rubocop>, [">= 0"])
    end
  else
    s.add_dependency(%q<ripper2ruby>, [">= 0"])
    s.add_dependency(%q<ruby2ruby>, [">= 0"])
    s.add_dependency(%q<sexp_processor>, [">= 0"])
    s.add_dependency(%q<ruby_parser>, [">= 0"])
    s.add_dependency(%q<ruby-graphviz>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rubocop>, [">= 0"])
  end
end

